//! `Cargo.lock` parser. Extracts `(name → version)` for every package
//! resolved from a registry source.
//!
//! Git / path / patch dependencies are skipped — they have no upstream
//! version to compare against, and OSV's `crates.io` ecosystem only
//! tracks crates.io releases. Filtering by `source = "registry+…"` keeps
//! the result aligned with what we already query.

use anyhow::Result;
use semver::Version;
use toml_edit::DocumentMut;

use super::Resolutions;

/// Parse `Cargo.lock` text into a `name → installed Version` map.
/// Unparseable versions and non-registry packages are silently skipped
/// — they're not actionable for vulnerability scanning.
pub fn parse(text: &str) -> Result<Resolutions> {
    let doc: DocumentMut = text.parse()?;
    let mut out = Resolutions::new();
    let Some(packages) = doc.get("package").and_then(|v| v.as_array_of_tables()) else {
        return Ok(out);
    };
    for tbl in packages.iter() {
        let source = tbl.get("source").and_then(|v| v.as_str()).unwrap_or("");
        if !source.starts_with("registry+") {
            continue;
        }
        let Some(name) = tbl.get("name").and_then(|v| v.as_str()) else {
            continue;
        };
        let Some(version) = tbl.get("version").and_then(|v| v.as_str()) else {
            continue;
        };
        let Ok(version) = Version::parse(version) else {
            continue;
        };
        // Workspace lockfiles can list the same package twice when two
        // members request incompatible versions; we keep the last entry
        // since we have no per-member context to disambiguate.
        out.insert(name.to_string(), version);
    }
    Ok(out)
}

#[cfg(test)]
mod tests {
    use super::*;
    use indoc::indoc;

    #[test]
    fn extracts_registry_packages() {
        let lock = indoc! {r#"
            # This file is automatically @generated by Cargo.

            [[package]]
            name = "serde"
            version = "1.0.228"
            source = "registry+https://github.com/rust-lang/crates.io-index"
            checksum = "abc"

            [[package]]
            name = "tokio"
            version = "1.35.1"
            source = "registry+https://github.com/rust-lang/crates.io-index"
            checksum = "def"
        "#};
        let res = parse(lock).unwrap();
        assert_eq!(res.get("serde"), Some(&Version::parse("1.0.228").unwrap()));
        assert_eq!(res.get("tokio"), Some(&Version::parse("1.35.1").unwrap()));
        assert_eq!(res.len(), 2);
    }

    #[test]
    fn skips_git_and_path_deps() {
        let lock = indoc! {r#"
            [[package]]
            name = "from-git"
            version = "0.1.0"
            source = "git+https://github.com/foo/bar.git#deadbeef"

            [[package]]
            name = "from-path"
            version = "0.2.0"
        "#};
        let res = parse(lock).unwrap();
        assert!(res.is_empty());
    }

    #[test]
    fn skips_unparseable_versions() {
        let lock = indoc! {r#"
            [[package]]
            name = "ok"
            version = "1.2.3"
            source = "registry+https://github.com/rust-lang/crates.io-index"

            [[package]]
            name = "weird"
            version = "definitely-not-semver"
            source = "registry+https://github.com/rust-lang/crates.io-index"
        "#};
        let res = parse(lock).unwrap();
        assert_eq!(res.len(), 1);
        assert!(res.contains_key("ok"));
    }

    #[test]
    fn empty_lockfile_returns_empty_map() {
        let res = parse("").unwrap();
        assert!(res.is_empty());
    }
}
